services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: .
    env_file: .env
    command: celery -A app.worker.a worker --loglevel=INFO
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airport_simulator
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  otel:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel.yaml"]
    volumes:
      - ./infra/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317"
volumes:
  pg:
